<?php

namespace ContainerKl9JFSS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VEbqy3hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VEbqy3h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VEbqy3h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'colorRepository' => ['privates', 'App\\Repository\\ColorRepository', 'getColorRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'vetementRepository' => ['privates', 'App\\Repository\\VetementRepository', 'getVetementRepositoryService', true],
        ], [
            'colorRepository' => 'App\\Repository\\ColorRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'vetementRepository' => 'App\\Repository\\VetementRepository',
        ]);
    }
}
