<?php

namespace Container6XaRR7f;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FPsfQyRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FPsfQyR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FPsfQyR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'colorRepository' => ['privates', 'App\\Repository\\ColorRepository', 'getColorRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'tagAmbianceRepository' => ['privates', 'App\\Repository\\TagAmbianceRepository', 'getTagAmbianceRepositoryService', true],
            'vetementRepository' => ['privates', 'App\\Repository\\VetementRepository', 'getVetementRepositoryService', true],
        ], [
            'colorRepository' => 'App\\Repository\\ColorRepository',
            'slugger' => '?',
            'tagAmbianceRepository' => 'App\\Repository\\TagAmbianceRepository',
            'vetementRepository' => 'App\\Repository\\VetementRepository',
        ]);
    }
}
