<?php

namespace Container6XaRR7f;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TGrh7JFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tGrh7JF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tGrh7JF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'vetementRepository' => ['privates', 'App\\Repository\\VetementRepository', 'getVetementRepositoryService', true],
        ], [
            'vetementRepository' => 'App\\Repository\\VetementRepository',
        ]);
    }
}
