<?php

namespace ContainerABjzx3Q;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GgO3p_IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GgO3p.I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GgO3p.I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'colorRepository' => ['privates', 'App\\Repository\\ColorRepository', 'getColorRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'paletteRepository' => ['privates', 'App\\Repository\\PaletteRepository', 'getPaletteRepositoryService', true],
            'referenceColorRepository' => ['privates', 'App\\Repository\\ReferenceColorRepository', 'getReferenceColorRepositoryService', true],
        ], [
            'colorRepository' => 'App\\Repository\\ColorRepository',
            'entityManager' => '?',
            'paletteRepository' => 'App\\Repository\\PaletteRepository',
            'referenceColorRepository' => 'App\\Repository\\ReferenceColorRepository',
        ]);
    }
}
