<?php

namespace ContainerQirlKly;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_472mcGHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.472mcGH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.472mcGH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'colorRepository' => ['privates', 'App\\Repository\\ColorRepository', 'getColorRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'vetementRepository' => ['privates', 'App\\Repository\\VetementRepository', 'getVetementRepositoryService', true],
        ], [
            'colorRepository' => 'App\\Repository\\ColorRepository',
            'slugger' => '?',
            'vetementRepository' => 'App\\Repository\\VetementRepository',
        ]);
    }
}
