<?php

namespace ContainerSPJp6x2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zfr_AygService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zfr.ayg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zfr.ayg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'colorRepository' => ['privates', 'App\\Repository\\ColorRepository', 'getColorRepositoryService', true],
            'paletteRepository' => ['privates', 'App\\Repository\\PaletteRepository', 'getPaletteRepositoryService', true],
            'vetementRepository' => ['privates', 'App\\Repository\\VetementRepository', 'getVetementRepositoryService', true],
        ], [
            'colorRepository' => 'App\\Repository\\ColorRepository',
            'paletteRepository' => 'App\\Repository\\PaletteRepository',
            'vetementRepository' => 'App\\Repository\\VetementRepository',
        ]);
    }
}
