<?php

namespace ContainerSPJp6x2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8LNhHdJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8LNhHdJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8LNhHdJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'referenceColorRepository' => ['privates', 'App\\Repository\\ReferenceColorRepository', 'getReferenceColorRepositoryService', true],
        ], [
            'referenceColorRepository' => 'App\\Repository\\ReferenceColorRepository',
        ]);
    }
}
