<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSPJp6x2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSPJp6x2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSPJp6x2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSPJp6x2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSPJp6x2\App_KernelDevDebugContainer([
    'container.build_hash' => 'SPJp6x2',
    'container.build_id' => 'a4a13d02',
    'container.build_time' => 1682448297,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSPJp6x2');
