<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDQxNju7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDQxNju7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDQxNju7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDQxNju7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDQxNju7\App_KernelDevDebugContainer([
    'container.build_hash' => 'DQxNju7',
    'container.build_id' => 'b4b247a1',
    'container.build_time' => 1682938688,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDQxNju7');
