<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_about' => [[], ['_controller' => 'App\\Controller\\AboutController::index'], [], [['text', '/about']], [], [], []],
    'app_accessibility' => [[], ['_controller' => 'App\\Controller\\AccessibilityController::index'], [], [['text', '/accessibility']], [], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], [], []],
    'app_colortest' => [[], ['_controller' => 'App\\Controller\\ColortestController::index'], [], [['text', '/colortest']], [], [], []],
    'app_dressing' => [[], ['_controller' => 'App\\Controller\\DressingController::index'], [], [['text', '/dressing']], [], [], []],
    'app_style' => [['type'], ['_controller' => 'App\\Controller\\DressingController::top'], [], [['variable', '/', '[^/]++', 'type', true], ['text', '/style']], [], [], []],
    'app_list-vetements' => [['type'], ['_controller' => 'App\\Controller\\DressingController::bottom'], [], [['variable', '/', '[^/]++', 'type', true], ['text', '/list-vetements']], [], [], []],
    'app_delete' => [['type', 'id'], ['_controller' => 'App\\Controller\\DressingController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['variable', '/', '[^/]++', 'type', true], ['text', '/delete']], [], [], []],
    'app_formulaire' => [[], ['_controller' => 'App\\Controller\\FormulaireController::index'], [], [['text', '/formulaire']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_generator' => [[], ['_controller' => 'App\\Controller\\HomeController::generator'], [], [['text', '/generator']], [], [], []],
    'app_join_us' => [[], ['_controller' => 'App\\Controller\\JoinUsController::index'], [], [['text', '/join/us']], [], [], []],
    'app_legal' => [[], ['_controller' => 'App\\Controller\\LegalController::index'], [], [['text', '/legal']], [], [], []],
    'app_privacy' => [[], ['_controller' => 'App\\Controller\\PrivacyController::index'], [], [['text', '/privacy']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'app_terms_of_use' => [[], ['_controller' => 'App\\Controller\\TermsOfUseController::index'], [], [['text', '/terms/of/use']], [], [], []],
    'app_testpalette' => [[], ['_controller' => 'App\\Controller\\TestpaletteController::index'], [], [['text', '/testpalette']], [], [], []],
    'app_testpalette_inte_backup' => [[], ['_controller' => 'App\\Controller\\TestpaletteController::integrationcolor'], [], [['text', '/integrationcolor/backup']], [], [], []],
    'app_testcolorname' => [['hexa1'], ['_controller' => 'App\\Controller\\TestpaletteController::colorname'], [], [['variable', '/', '[^/]++', 'hexa1', true], ['text', '/testcolorname']], [], [], []],
    'app_user' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user']], [], [], []],
    'app_vetement' => [[], ['_controller' => 'App\\Controller\\VetementController::index'], [], [['text', '/vetement']], [], [], []],
    'app_hsl' => [['h', 's', 'l'], ['_controller' => 'App\\Controller\\VetementController::hsl'], [], [['text', '/'], ['variable', '/', '[^/]++', 'l', true], ['variable', '/', '[^/]++', 's', true], ['variable', '/', '[^/]++', 'h', true], ['text', '/hsl']], [], [], []],
];
